version: '3'

services:
    # nginx:
    #     image: nginx:latest
    #     restart: always
    #     ports:
    #         - "$NGINX_EXPOSE_PORT:80"
    #     volumes:
    #         - ./:/var/www/html
    #         - ./docker/nginx/conf.d:/etc/nginx/conf.d
    #         - ./logs/nginx:/var/log/nginx
    #     healthcheck:
    #         test: ["CMD", "service", "nginx", "status"]
    #         retries: 3
    #         timeout: 5s
    websocket:
        build: ./
        restart: always
        ports:
            - "$WEBSOCKET_PORT:$WEBSOCKET_PORT"
            
